### ISSUE TITLE
Can not find css and js files

### ISSUE THREAD

**Issue by bmbBAMBUS** [webdevmatics/ecom#1]
php artisan serve logs show that "there is no such file or directory"  for all files in /dist folder, but they are there. I work on Windows so I haven't to set chmoods for this directory I think. Page is displaying but without css and js.
What did I do wrong? Please advise.

**Comment by webdevmatics** [comment]
Do you have any errors on console?

**Comment by bmbBAMBUS** [comment]
It was my fault, because of of second project on the same vhost, I guess. Now everything works fine. Thanks for time and great field to learn laravel.
