### ISSUE TITLE
There are two tables with the same name?

### ISSUE THREAD

**Issue by obaaa8** [webdevmatics/ecom#3]
`In 2016_12_10_071213_create_categories_table.php line 32:

  Cannot declare class CreateCategoriesTable, because the name is already in use`

**Comment by webdevmatics** [comment]
That was updated to product_categories I will push fix very soon.

**Comment by brnrajoriya** [comment]
I am also facing this issue. Still waiting for the next updates.

**Comment by BBEDERRAR** [comment]
we are waiting the next update !!!

**Comment by webdevmatics** [comment]
Let me push the code
